const skills = [
    { image: "skills/html.png" },
    { image: "skills/css.png" },
    { image: "skills/js.png" },
    // { image: "skills/c.png" },
    { image: "skills/c++.png" },
    // { image: "skills/c-sharp.png" },
    { image: "skills/python.png" },
    { image: "skills/java.png" },
    { image: "skills/nodejs.png" },
    { image: "skills/react.png" },
    { image: "skills/Redux.png" },
    // { image: "skills/aspnet.png" },
    { image: "skills/Django.png" },
    // { image: "skills/sql-server.png" },
    { image: "skills/tailwindcss.svg" },
    // { image: "skills/bootstrap.png" }, 
    { image: "skills/MySQL.png" }, 
    { image: "skills/MongoDB.png" }, 
    { image: "skills/Linux.png" }, 
    { image: "skills/Git.png" }, 
    { image: "skills/Postman.png" }, 
  ];

export default skills;